package com.grade.entity;

import java.util.Date;

public class Students {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.xh
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private Integer xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.name
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.age
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.address
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.birthday
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.state
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.gid
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sex
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.xh
     *
     * @return the value of students.xh
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.xh
     *
     * @param xh the value for students.xh
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.name
     *
     * @return the value of students.name
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.name
     *
     * @param name the value for students.name
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.age
     *
     * @return the value of students.age
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.age
     *
     * @param age the value for students.age
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.address
     *
     * @return the value of students.address
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.address
     *
     * @param address the value for students.address
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.birthday
     *
     * @return the value of students.birthday
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.birthday
     *
     * @param birthday the value for students.birthday
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.state
     *
     * @return the value of students.state
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.state
     *
     * @param state the value for students.state
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.gid
     *
     * @return the value of students.gid
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.gid
     *
     * @param gid the value for students.gid
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sex
     *
     * @return the value of students.sex
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sex
     *
     * @param sex the value for students.sex
     *
     * @mbggenerated Sun Aug 19 10:54:38 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}